- name: install node modules
  npm: name={{item}} global=yes
  with_items:
    - bower
    - slush

- name: install python requirements
  pip: requirements=/vagrant/src/requirements.txt

- name: install slush generators
  sudo: yes
  shell: cd /vagrant && ./provisioning/install-slush-generators.sh
